### ISSUE TITLE
Add global filters

### ISSUE THREAD

**Issue by zhafen** [ageller/Firefly#10]
It would be really nice to have a "global" filter that applies a filter onto all different particle types. For example, if we're looking at gas particles broken down into two classifications it would be nice to choose only the highest metallicity particles from both types. This is a frequent issue for particle tracking data sets, and currently each classification has to be filtered one-by-one.

Note that the filter probably shouldn't truly global, but should be applied to a subset of the particle types. This is necessary when displaying, for example, star data alongside two types of gas data.

**Comment by agurvich** [comment]
realistically, this quality of life feature (QoL b.c. the functionality exists it's just obnoxious to set filters for each particle group) could introduce weird bugs, would require that we  fundamentally alter the filtering structure or introduce some kind of particle group hierarchy where you can link particle groups to other ones.... it's all very complicated for something that we've gotten 3 years into the future without truly needing. sorry zach
