### ISSUE TITLE
Filters doesn't always work when switching on and off particle types

### ISSUE THREAD

**Issue by zhafen** [ageller/Firefly#11]
Applying filters to a particle type, turning off that particle type, and turning back on the particle type resets the view and displays all particles, including filtered particles. To cause the filtered particles to disappear, you have to modify one of the existing filters ever so slightly, which then causes all the filters to start working again.

**Comment by ageller** [comment]
Good catch.  Just fixed it.

**Comment by zhafen** [comment]
Hey Aaron, I'm still encountering this issue, including with the latest version of Firefly.

**Comment by ageller** [comment]
Sorry, I wonder if I broke it sometime after fixing it?  Anyway, I'm pretty sure it is fixed now!

**Comment by zhafen** [comment]
@ageller , works great now, thanks!
