### ISSUE TITLE
[Doc] Example in the documentation does not work

### ISSUE THREAD

**Issue by JulienPeloton** [ageller/Firefly#126]
Thanks for the nice package, it looks promising!

I followed the documentation to create my own instance of Firefly (https://ageller.github.io/Firefly/docs/build/html/data_reader/index.html), and I encountered some problems that I list here:

### Typo in the import

```python
# currently
from firefly.data_reader import ArrayReader

# should be
from Firefly.data_reader import ArrayReader
```

### JSONDecodeError

Following the example, I executed:

```python
import os
import numpy as np
from Firefly.data_reader import ArrayReader
from Firefly.server import spawnFireflyServer

coords = np.random.random(size=(10000,3))
fields = np.random.random(size=coords[:,0].size)

# data folder created before
JSONdir = os.environ['PWD'] + '/data'

# Output it to a Firefly-compatible JSON!
my_arrayReader = ArrayReader(
    coords,
    fields = fields,
    JSONdir = JSONdir,
    write_jsons_to_disk = True
)

process = spawnFireflyServer()
my_arrayReader.sendDataViaFlask()
```

and I get the following error:

```
palettable colormaps are not installed
don't have phil's colormaps
JSONdir: /home/peloton/workspace/firefly/data -- is not a sub-directory of Firefly/static/data. 
This may produce confusing or inoperable results. As such, we will create a symlink for you when you  dumpToJSON.
Make sure each tracked_array (1) has a tracked_filter_flag (0), assuming True.
Make sure each tracked_array (1) has a tracked_colormap_flag (0), assuming True.
Outputting: PGroup_0 - 10000/10000 particles - 1 tracked fields
Waiting up to 10 seconds for background Firefly server to startdone! Your server is available at - http://localhost:5000
======= showing loader
======= receiving data from server ...
======= size of data 49
[2022-07-29 08:02:19,943] ERROR in app: Exception on /data_input [POST]
Traceback (most recent call last):
  File "/home/peloton/anaconda3/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/peloton/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/peloton/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/peloton/anaconda3/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/peloton/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/peloton/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/peloton/anaconda3/lib/python3.9/site-packages/Firefly/server.py", line 203, in data_input
    data = json.loads(jsondata)
  File "/home/peloton/anaconda3/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/peloton/anaconda3/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/peloton/anaconda3/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Posting...data posted!
Invalid session ozPjj33O549zAriAAAAA (further occurrences of this error will be logged with level INFO)
Invalid session Xp72TNZgcMawNLLRAAAE (further occurrences of this error will be logged with level INFO)
======= connected {'data': 'GUI connected!'}
======= connected {'data': 'Viewer connected!'}
```

The index page is accessible though, but it says `loading` forever. Any ideas?

![Screenshot 2022-07-29 at 08-04-26 Firefly](https://user-images.githubusercontent.com/20426972/181693581-87f9b5e5-c29d-4915-9eb5-173760884699.png)

Setup
- Ubuntu 20.04
- Python 3.9.12
- Firefly installed via pip today (no version given)

**Comment by ddhendriks** [comment]
I am encountering issues with the installation as well:

```
Traceback (most recent call last):
  File "/home/david/projects/firefly_test/script/test.py", line 16, in <module>
    from firefly.data_reader import ArrayReader
  File "/home/david/.pyenv/versions/3.9.9/lib/python3.9/site-packages/firefly-3.1.0-py3.9.egg/firefly/data_reader/__init__.py", line 1, in <module>
    from .reader import Reader,SimpleReader,ArrayReader
  File "/home/david/.pyenv/versions/3.9.9/lib/python3.9/site-packages/firefly-3.1.0-py3.9.egg/firefly/data_reader/reader.py", line 11, in <module>
    from .particlegroup import ParticleGroup
  File "/home/david/.pyenv/versions/3.9.9/lib/python3.9/site-packages/firefly-3.1.0-py3.9.egg/firefly/data_reader/particlegroup.py", line 10, in <module>
    from .octree import Octree, init_octree_root_node
  File "/home/david/.pyenv/versions/3.9.9/lib/python3.9/site-packages/firefly-3.1.0-py3.9.egg/firefly/data_reader/octree.py", line 12, in <module>
    from abg_python.system_utils import printProgressBar
ImportError: cannot import name 'printProgressBar' from 'abg_python.system_utils' (/home/david/.pyenv/versions/3.9.9/lib/python3.9/site-packages/abg_python-1.0.5-py3.9.egg/abg_python/system_utils.py)
```

Running 
```
import abg_python
print(dir(abg_python.system_utils))

```

gives 

```
['StringIO', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'get_size', 'getfinsnapnum', 'os', 'suppressSTDOUTToFile', 'sys']
```

I think this is because the version of abg_python that is available on pip does not have the progressbar implementation.

**Comment by agurvich** [comment]
@ddhendriks good catch 😅 just updated `abg_python` to 1.0.6 and `firefly` to `3.1.1` to track the progress bar implementation.

**Comment by JulienPeloton** [comment]
Hi @agurvich -- is it normal that `firefly` version on pip is still 2.0.4?
https://pypi.org/project/Firefly-vis/

The versions 3.x do not seem to appear (which is maybe the reason for my error above)

**Comment by agurvich** [comment]
🙀 you want: https://pypi.org/project/firefly/, where in the documentation have I pointed to `Firefly-vis` that must be squashed!!

**Comment by JulienPeloton** [comment]
ah ah I was reading the wrong link then. That explains a lot :D

Except the href in the badge, and the installation page (https://ageller.github.io/Firefly/docs/build/html/installation.html), I do not find it anywhere else.

**Comment by JulienPeloton** [comment]
But then the doc at https://ageller.github.io/Firefly/docs/build/html/data_reader/index.html is not in line with version 3.x, e.g.
- capitalised imports
- ArrayReader arguments (`write_jsons_to_disk` does not exist)

**Comment by agurvich** [comment]
😭 yes you're absolutely correct, the documentation is not up-to-date... I will point it to the correct API asap (`write_jsons_to_disk` became `writeToDisk` but I'm sure there's other backwards incompatible things I changed from version 2.x to 3.x)

**Comment by agurvich** [comment]
Even still, I'm getting the same "Unexpected token / in JSON" error that you were getting while trying to run the minimal example. so it's not just a version issue...

**Comment by agurvich** [comment]
Alright, I fixed the unexpected token error. 

@ageller It turns out it was trying to pass binary data through the `data_input` endpoint when it should've been sending `.json`. When we write binary data we always write to disk so the "json" data being passed through flask was actually the path on disk, the unexpected token was actually the the first character in the absolute path to the data on disk 😬 

that led me to another error where options files were being turned into particle meshes. We had anticipated this and removed options from the `viewerParams.partsKeys` but when I added a guard to sanitize particle group names I was putting them back into the `viewerParams.partsKeys` list (but only when `loadData` was passed a callback, which happens IFF we use `sendDataViaFlask`-- not sure I understand what's up with that). Regardless, I put a conditional that I *think* will stop options and tweenParams files from being added back to `viewerParams.partsKeys`. 

@JulienPeloton I'll go ahead and update the documentation now so you can actually try it out and let me know if you're getting the same unexpected token error.

**Comment by agurvich** [comment]
@JulienPeloton I think the docs should be updated now, let me know if you find anything that isn't working. Once you get your minimal example going LMK and we can close the issue!

**Comment by JulienPeloton** [comment]
Thanks @agurvich -- the example works in the sense that nothing crashes, but the display always shows me the same things (no matter what `coords` is):

![Screenshot 2022-07-29 at 22-42-56 Untitled - Jupyter Notebook](https://user-images.githubusercontent.com/20426972/181840323-4abf82d1-b491-4536-99f4-800225ee357f.png)

Is it due to the warning:

```
datadir is None, defaulting to /home/peloton/anaconda3/lib/python3.9/site-packages/firefly/static/data/Data
```
?

**Comment by JulienPeloton** [comment]
Ah wait, I forgot the last cell... but then I have an error:
![Screenshot 2022-07-29 at 22-46-03 Untitled - Jupyter Notebook](https://user-images.githubusercontent.com/20426972/181840733-fc145ea1-a538-40b2-9f0d-d8c4b049707b.png)

Indeed, the default port should be 5500, not 5000. So forcing the port:
![Screenshot 2022-07-29 at 22-46-25 Untitled - Jupyter Notebook](https://user-images.githubusercontent.com/20426972/181840781-d2f1a376-87e1-4c6f-857a-6a8b415858cc.png)

hum, any ideas?

**Comment by agurvich** [comment]
Yes! That is the problem I fixed this morning:

>that led me to another error where options files were being turned into particle meshes. We had anticipated this and removed options from the viewerParams.partsKeys but when I added a guard to sanitize particle group names I was putting them back into the viewerParams.partsKeys list (but only when loadData was passed a callback, which happens IFF we use sendDataViaFlask-- not sure I understand what's up with that). Regardless, I put a conditional that I think will stop options and tweenParams files from being added back to viewerParams.partsKeys.

Either: 
1. you need to update to 3.1.2
2. I need to upload 3.1.3 to pypi which actually contains the fix 😅 

let me know what version you're running and we can figure out whether we're in regime 1 or 2

**Comment by agurvich** [comment]
The datadir warning is just telling you that your data is being saved somewhere you might not like it to be. If you want to get rid of that pass the `datadir=` kwarg and then you'll get a *different* warning that we'll have to make a symlink to that directory for everything to work.

**Comment by JulienPeloton** [comment]
Ah wait -- with the new 3.1.2 version, all good :tada: Thanks @agurvich for the quick fixes!

**Comment by agurvich** [comment]
No problem! let's close this bad boy and you can open up another if/when you find something else I broke 🙃

**Comment by JulienPeloton** [comment]
Perfect! Sorry for the long thread :D
