### ISSUE TITLE
screenshot should not crop the image if aspect ratio is the same

### ISSUE THREAD

**Issue by agurvich** [ageller/Firefly#139]
likewise, the # of pixels should be upsampling/downsampling not increasing the field of view (as it currently is)

**Comment by agurvich** [comment]
https://github.com/ageller/Scatter_WebGL

has a working implementation of this and @ageller said he would copy it over

**Comment by ageller** [comment]
This was either inadvertently fixed or was never actually an issue.  Works now as expected.
