### ISSUE TITLE
loading from preset is broken? 

### ISSUE THREAD

**Issue by ageller** [ageller/Firefly#155]
I tried saving and loading a preset in the SDSS example (linked in our gallery).  I moved the camera and changed the particle sizes then saved a preset.  Saving the preset worked fine; I'll attach the preset file here (which maybe we should name settings.json instead?) .  After reloading the page and then loading in the preset file, the camera was positioned correctly and the particles were sized correctly, but the GUI disappeared.  Looking at the developer tools showed an error un UI.js (and then my computer crashed! <--so I suppose it's possible that this is only an issue on my end...)  

Note: GitHub won't allow me to attach a json file, so I renamed this to preset.txt :)

[preset.txt](https://github.com/ageller/Firefly/files/10279690/preset.txt)

**Comment by agurvich** [comment]
issue was that SDSS example was not using updated source. works now fine.
