### ISSUE TITLE
crash screen fires when tab is not visible (in chrome)

### ISSUE THREAD

**Issue by ageller** [ageller/Firefly#16]
If the Firefly tab is not visible, I believe the default is that nothing will be drawn.  Therefore, if the tab window is not visible for the time limit you've enabled for the crash screen, it will display the crash screen when we go back to the tab.  This is obviously not desirable.

**Comment by zhafen** [comment]
To add onto this, saving a preset will also crash it, for similar reasons. Alex and I talked about this, and the solution may be to just add a button that allows you to resume animation for Firefly. If it really has crashed, then it will just crash again, and that's okay.

**Comment by agurvich** [comment]
one simple fix would be to pause the passage of time in the real world when you tab out, @ageller, let me know when you get around to this.

**Comment by ageller** [comment]
In that case, maybe it shouldn't be thought of as a crash.  The screen could say something like "Hmmm, it seems like Firefly has taken a long time between renderings, want to continue?". 

And HA!  this is @agurvich 's project, he can fix it :) . But wow, wouldn't it be great if we could really "pause the passage of time in the real world"

**Comment by agurvich** [comment]
did exactly that.
