### ISSUE TITLE
defaultsettings filename mismatch

### ISSUE THREAD

**Issue by marlena6** [ageller/Firefly#169]
Just starting out using firefly and recently installed it (within the last ~week). I had an issue trying to import SimpleFireReader and ArrayReader that traced to a capitalized D for `DefaultSettings.json` and  `DefaultParticleSettings.json` in lines 638 and 642 of firefly/data_reader/settings.py, whereas the corresponding files in firefly/static/js/misc/ start with lowercase d. Changing the capitalization fixed the issue.

**Comment by agurvich** [comment]
🤦🏻 thank you for catching that...

**Comment by agurvich** [comment]
I'll update the version on pypi as well!!

**Comment by agurvich** [comment]
Okay, 3.2.1 should be live here and on Pypi. Cheers!!

**Comment by marlena6** [comment]
Great, thank you!
