### ISSUE TITLE
Presets don't work at all

### ISSUE THREAD

**Issue by zhafen** [ageller/Firefly#17]
The screen turns black and the data becomes unresponsive. This can be reproduced in [the online version of Firefly](https://ageller.github.io/Firefly/).

**Comment by zhafen** [comment]
Here's the error:
```
Uncaught Error: noUiSlider (10.0.0): nouislider.min.js:3 'range' value isn't numeric.
    at A (nouislider.min.js:3)
    at new C (nouislider.min.js:3)
    at Object.F [as t] (nouislider.min.js:3)
    at nouislider.min.js:3
    at Array.forEach (<anonymous>)
    at X (nouislider.min.js:3)
    at Object.Z [as create] (nouislider.min.js:3)
    at createPsliders (UI.js:611)
    at createUI (UI.js:1860)
    at resetToPreset (UI.js:95)
```

**Comment by agurvich** [comment]
Perhaps related to adding the colormap variables presets do not work at all, uh oh

**Comment by agurvich** [comment]
used to be that you couldn't use presets at all. as of (insert commit here) you can now use presets that were made in the python front end. 

but you can't export presets from the app and use those, for some reason... 

maybe related to colormapLims and colormapVals?

**Comment by agurvich** [comment]
we should try and see if the colormap vals and colormap lims as set in the python frontend are actualized in Firefly or if they are just ignored (even better if there's an error message!)

**Comment by agurvich** [comment]
hooks exist in [flaskGUI] for colormap, showColormap, and colormap variable. 

I fixed velocity vectors as well in [abgGreece] but that still needs to be transferred over to [flaskGUI]
