### ISSUE TITLE
Flask as a server for separate UI and viz

### ISSUE THREAD

**Issue by ageller** [ageller/Firefly#18]
Frank suggests that we use Flask (through python) to create a server that will allow us to host the UI and visualization on a separate port that communicate with each other (e.g., for UI on an ipad and viz on the computer).  This would be great for the Adler, and also any kind of visualization wall.  Though we would still need to maintain the current version for most users.

**Comment by agurvich** [comment]
Does using Flask mean we would have to use frozen versions of Firefly for that? I guess I mean to say: what is Flask, haha

**Comment by ageller** [comment]
http://flask.pocoo.org/docs/1.0/

And I really don't know how it works (yet!).  But we'd definitely want to do our best to keep both versions (if we need 2 versions) updated simultaneously.  *Maybe* we can simply create two new .html files (one for loading the UI, and another for loading the viz).  These files could call the same .js files that we use in our standard index.html.

**Comment by agurvich** [comment]
Aha, I noticed: "http://flask.pocoo.org/docs/1.0/signals/" which seems relevant. I'll take a look at this then because I agree, decoupling the UI will definitely improve presentation. Speaking of which...

**Comment by ageller** [comment]
Sounds like we'd have to dramatically modify the UI, however, to use forms.  Frank is interested in helping, though maybe not until winter.  This does have additional benefits because, for instance, our "presets" could also be represented by a very long URL (like in google maps).
