### ISSUE TITLE
Navigating away from Firefly when the page is loading causes crash

### ISSUE THREAD

**Issue by zhafen** [ageller/Firefly#20]
Tabbing out of Firefly will bring up the "Firefly has gone to sleep screen". However, if you tab out of Firefly while the dataset is loading you can't exit the sleep screen when you return (can't click anything), and are forced to reload the page. This is an issue for larger datasets that take a while to load, where the user will be tempted to tab out for a second.

**Comment by agurvich** [comment]
just had to fix z-order so the click wasn't being eaten by the wrong div. all better now!
