### ISSUE TITLE
Filter playback can be turned on, but not off

### ISSUE THREAD

**Issue by zhafen** [ageller/Firefly#23]
If you turn the "Playback" option on for a filter the option to turn it off again disappears in the UI. See the relevant screenshot.

![Playback toggle missing](https://user-images.githubusercontent.com/8739972/51885775-e0085680-2341-11e9-8c87-cb715293cab0.png)

**Comment by agurvich** [comment]
Likely an issue with how we define the height of the particle group's box with the new colormap slider. I suspect somebody hard coded in a height... I'll take a look

**Comment by agurvich** [comment]
fixed in [flaskGUI] (and also the dead commits that will never see the light of day from [abgGreece])
