### ISSUE TITLE
Filters don't always work when manipulating the colormap

### ISSUE THREAD

**Issue by zhafen** [ageller/Firefly#24]
Exact same as Issue #11 , except the action of manipulating the colormap is what resets the view and displays all particles, even filtered particles. The live version of Firefly currently displays this behavior.

**Comment by agurvich** [comment]
indeed, it seems like changing the colormap slider ignores any applied filters.

**Comment by agurvich** [comment]
@ageller when the colormap slider is adjusted it totally ignores the filter settings-- it is pretty jarring. do you remember how you fixed this before?

**Comment by ageller** [comment]
Fixed.  I had set the transparent flag in the ShaderMaterial to false for the colormap, but we need the ability to set the alpha value to hide the particles when filtering.  I tried a bunch of other things before realizing this was the issue, hence some minor changes in other files.  But I *think* simply setting "transp = true" on line 48 in draw.js, may have been all that was needed.

**Comment by agurvich** [comment]
did we go back to setting the transparency for filtered particles instead of setting the size to 0? I vaguely remember doing this but I don't remember why...

**Comment by agurvich** [comment]
Was that to improve latency on moving the slider? why is it faster to change the alpha value vs. changing the particle size? I seem to remember that we don't have to re-filter when changing alpha but we do when changing the particle size.... is that because we are just setting alpha either to 0/1 and the particle size we have to go back to the data when we want to show it again?

**Comment by ageller** [comment]
We do both, but it looks like the points will never actually be zero in size (there is some minimum size).  So from far away, even if the points are all size 0, they are all visible and about the same size as points that are large when closer up.  This does reduce time in blending though, so it's good to keep it.  Setting alpha=0 removed the point from view.  

Yes, this improves the latency on sliders.  The other option is to redraw every time you move the slider.  That is very slow.  (Setting alpha = 0 and size = 0 are both done in renderAll.js, and they both are very quick.)

In terms of changing the particle size from the UI slider, this also does not require a full redraw, it just changes the PsizeMult uniform variable in the shader.

**Comment by agurvich** [comment]
Oh I didn't realize there was a minimum size when you're zoomed out-- that all makes sense now, thanks! 

However, this reminds me that I've noticed something else which I'll raise as another issue and I'll show you when I get back in town.
