### ISSUE TITLE
.git folder is exploding with old data

### ISSUE THREAD

**Issue by agurvich** [ageller/Firefly#31]
we need to reduce the size of the pack files from 700 Mb before Aaron's git account is destroyed

see:
https://stackoverflow.com/questions/11050265/remove-large-pack-file-created-by-git

**Comment by ageller** [comment]
This may also be helpful:

https://stackoverflow.com/questions/40697663/show-commit-size-in-git-log

**Comment by ageller** [comment]
This too https://stackoverflow.com/questions/1314950/git-get-all-commits-and-blobs-they-created/1318854#1318854

**Comment by ageller** [comment]
And this https://support.acquia.com/hc/en-us/articles/360004334093-Removing-large-files-from-Git-without-losing-history

Maybe we can just remove all particle data sets from all commits, and then add back the current set?

**Comment by agurvich** [comment]
That second one looks promising, good find.
