### ISSUE TITLE
camera flips itself upside down in flask detached UI when orbiting

### ISSUE THREAD

**Issue by agurvich** [ageller/Firefly#41]
when camera changes orbits it instead flips upside down and reverses orbit, very disorienting. easily demonstrated in person, @ageller

**Comment by agurvich** [comment]
update: it only happens when you can see the green/red face of the cube-- not sure which axes it's crossing when you can see those faces

**Comment by ageller** [comment]
Fixed.  I forgot to set camera.up in viewer.  I did that, and now it works.
