### ISSUE TITLE
Throttle Firefly before it crashes your computer

### ISSUE THREAD

**Issue by agurvich** [ageller/Firefly#7]
Can we measure time between frames being drawn and throttle the number of particles to prevent Firefly from crashing a user's device when they "ask too much" of it.

**Comment by agurvich** [comment]
@ageller, can we have something in `update` that checks the current time and saves it into `params`-- then at the next tick of `update` checks the current time with the one saved in `params` and if too long has passed since the last call to update it will close the canvas and revert to a splash screen that says Firefly has crashed? How do we close the canvas/break the animation loop?

**Comment by ageller** [comment]
if params.pauseAnimation == true, I believe this will stop updating.  This is currently not used, but could be perfect for this case, if you want to try to build this in as you describe.  params.pauseAnimation is checked in the animate function within renderAll.js .

**Comment by agurvich** [comment]
works! i have it checking if it takes more than 1 second and pausing the animation. Could even restart the animation by having a button. should also pop up a splash screen but I don't know how to do that...

**Comment by agurvich** [comment]
i added a crash screen that just asks you to reload the page... I looked into interrupting the `renderer.render` call but I was really struggling to find anything. There was something about bluebird.js and promises that seemed like you could wrap the function call in a promise and set a timeout but I didn't really understand it.

**Comment by agurvich** [comment]
This element of the feature is as good as it's going to get. New ideas for restricting user input to make app more stable should be organized as separate issues.
