### ISSUE TITLE
Fly checkbox

### ISSUE THREAD

**Issue by ageller** [ageller/Firefly#8]
Pressing space bar (a) doesn't toggle the checkbox in camera controls, and (b) will toggle the dropdown instead if you're clicked in the UI (maybe b is not fixable).  Related to (b), you also have to click into the canvas after clicking the checkbox for controls to work (also maybe difficult to fix)

**Comment by agurvich** [comment]
is this issue closed or is there more to do?

**Comment by ageller** [comment]
I left it open in case we want to try to fix the extra click into the canvas after clicking on the checkbox (though I don't know if we can get around this).  Feel free to close, if you're happy with the functionality at this point.

**Comment by agurvich** [comment]
I agree that I am uncertain if we can fix that, since it would require somehow changing the "focus" back to the canvas after clicking that checkbox in the UI (and only that checkbox?). I'll go ahead and close.
